import { QuestionDef } from '../../types/assessment';

export const questions: QuestionDef[] = [
    {
      id: 'weight_goal',
      section: 'Goal & Motivation',
      label: 'What is your primary weight goal?',
      type: 'single_choice',
      options: [
        { id: 'lose', label: '🔥 Lose Weight', value: 'lose' },
        { id: 'maintain', label: '⚖️ Maintain Weight', value: 'maintain' },
        { id: 'gain', label: '📈 Gain Weight', value: 'gain' },
        { id: 'recomp', label: '💪 Improve Body Composition', value: 'recomp' },
      ],
      required: true,
    },
    {
      id: 'target_weight',
      section: 'Goal & Motivation',
      label: 'What is your target weight?',
      type: 'weight',
      required: true,
    },
    {
      id: 'goal_timeline',
      section: 'Goal & Motivation',
      label: 'When would you ideally like to reach your goal?',
      type: 'single_choice',
      options: [
        { id: '1m', label: '🚀 Within 1 month', value: '1m' },
        { id: '3m', label: '📅 2–3 months', value: '3m' },
        { id: '6m', label: '📆 3–6 months', value: '6m' },
        { id: '12m', label: '🗓️ 6–12 months', value: '12m' },
        { id: 'none', label: '⏳ No fixed timeline', value: 'none' },
      ],
    },
    {
      id: 'weight_history',
      section: 'Weight History',
      label: 'Has your weight changed during the last 12 months?',
      type: 'single_choice',
      options: [
        { id: 'lost_10', label: '📉 Lost more than 10 kg', value: 'lost_10' },
        { id: 'lost_5', label: '📉 Lost 5–10 kg', value: 'lost_5' },
        { id: 'stable', label: '⚖️ Stable', value: 'stable' },
        { id: 'gained_5', label: '📈 Gained 5–10 kg', value: 'gained_5' },
        { id: 'gained_10', label: '📈 Gained more than 10 kg', value: 'gained_10' },
      ],
    },
    {
      id: 'weight_attempts',
      section: 'Weight History',
      label: 'How many times have you seriously tried to change your weight?',
      type: 'single_choice',
      options: [
        { id: '0', label: '🚫 Never', value: '0' },
        { id: '1', label: '☝️ Once', value: '1' },
        { id: '2_3', label: '🔁 2–3 times', value: '2_3' },
        { id: '3_plus', label: '♾️ More than 3 times', value: '3_plus' },
      ],
    },
    {
      id: 'biggest_obstacle',
      section: 'Weight History',
      label: 'What do you believe is your biggest obstacle?',
      type: 'single_choice',
      options: [
        { id: 'overeating', label: '🍔 Overeating', value: 'overeating' },
        { id: 'cravings', label: '🍩 Cravings', value: 'cravings' },
        { id: 'schedule', label: '⏱️ Busy schedule', value: 'schedule' },
        { id: 'exercise', label: '🛋️ Lack of exercise', value: 'exercise' },
        { id: 'stress', label: '🤯 Stress', value: 'stress' },
        { id: 'sleep', label: '🥱 Poor sleep', value: 'sleep' },
        { id: 'medical', label: '🏥 Medical reasons', value: 'medical' },
        { id: 'dont_know', label: "Don't know", value: 'dont_know' },
      ],
    },
    {
      id: 'meals_per_day',
      section: 'Eating Habits',
      label: 'How many meals do you eat each day?',
      type: 'single_choice',
      options: [
        { id: '1', label: '1', value: '1' },
        { id: '2', label: '2', value: '2' },
        { id: '3', label: '3', value: '3' },
        { id: '4', label: '4', value: '4' },
        { id: '5_plus', label: '5+', value: '5_plus' },
      ],
    },
    {
      id: 'skip_breakfast',
      section: 'Eating Habits',
      label: 'How often do you skip breakfast?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'sometimes', label: '➖ Sometimes', value: 'sometimes' },
        { id: 'often', label: '📈 Often', value: 'often' },
        { id: 'daily', label: '🔁 Daily', value: 'daily' },
      ],
    },
    {
      id: 'snacking_frequency',
      section: 'Eating Habits',
      label: 'How often do you snack between meals?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'sometimes', label: '➖ Sometimes', value: 'sometimes' },
        { id: 'often', label: '📈 Often', value: 'often' },
        { id: 'multiple', label: '♾️ Multiple times/day', value: 'multiple' },
      ],
    },
    {
      id: 'late_eating',
      section: 'Eating Habits',
      label: 'How often do you eat late at night (within 2 hours of bedtime)?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'sometimes', label: '➖ Sometimes', value: 'sometimes' },
        { id: 'often', label: '📈 Often', value: 'often' },
        { id: 'daily', label: '🔁 Daily', value: 'daily' },
      ],
    },
    {
      id: 'eating_out',
      section: 'Eating Habits',
      label: 'How often do you eat restaurant, takeaway, or fast food?',
      type: 'single_choice',
      options: [
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'weekly', label: '📅 Weekly', value: 'weekly' },
        { id: '2_3', label: '🗓️ 2–3 times/week', value: '2_3' },
        { id: '4_plus', label: '📆 4+ times/week', value: '4_plus' },
        { id: 'daily', label: '🔁 Almost daily', value: 'daily' },
      ],
    },
    {
      id: 'sugary_drinks',
      section: 'Eating Habits',
      label: 'How often do you consume sugary drinks?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'weekly', label: '📅 Weekly', value: 'weekly' },
        { id: 'few_times', label: '🗓️ Few times/week', value: 'few_times' },
        { id: 'daily', label: '🔁 Daily', value: 'daily' },
        { id: 'multiple', label: 'Multiple/day', value: 'multiple' },
      ],
    },
    {
      id: 'portion_sizes',
      section: 'Eating Habits',
      label: 'How would you describe your portion sizes?',
      type: 'single_choice',
      options: [
        { id: 'small', label: '🐁 Small', value: 'small' },
        { id: 'moderate', label: '🐕 Moderate', value: 'moderate' },
        { id: 'large', label: '🐘 Large', value: 'large' },
        { id: 'very_large', label: '🐋 Very Large', value: 'very_large' },
        { id: 'not_sure', label: '🤷 Not Sure', value: 'not_sure' },
      ],
    },
    {
      id: 'cravings_freq',
      section: 'Hunger & Cravings',
      label: 'How often do you experience strong food cravings?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'sometimes', label: '➖ Sometimes', value: 'sometimes' },
        { id: 'often', label: '📈 Often', value: 'often' },
        { id: 'daily', label: '🔁 Daily', value: 'daily' },
      ],
    },
    {
      id: 'cravings_time',
      section: 'Hunger & Cravings',
      label: 'When are cravings strongest?',
      type: 'single_choice',
      options: [
        { id: 'morning', label: '🌅 Morning', value: 'morning' },
        { id: 'afternoon', label: '☀️ Afternoon', value: 'afternoon' },
        { id: 'evening', label: '🌆 Evening', value: 'evening' },
        { id: 'late_night', label: '🌙 Late Night', value: 'late_night' },
        { id: 'random', label: '🎲 Random', value: 'random' },
      ],
    },
    {
      id: 'emotional_eating',
      section: 'Hunger & Cravings',
      label: 'Do you eat when you are stressed, bored, or emotional?',
      type: 'single_choice',
      options: [
        { id: 'never', label: '🚫 Never', value: 'never' },
        { id: 'rarely', label: '📉 Rarely', value: 'rarely' },
        { id: 'sometimes', label: '➖ Sometimes', value: 'sometimes' },
        { id: 'often', label: '📈 Often', value: 'often' },
        { id: 'always', label: '💯 Almost Always', value: 'always' },
      ],
    },
    {
      id: 'sleep_hours',
      section: 'Lifestyle',
      label: 'On average, how many hours do you sleep each night?',
      type: 'single_choice',
      options: [
        { id: 'less_5', label: 'Less than 5', value: 'less_5' },
        { id: '5_6', label: '5–6', value: '5_6' },
        { id: '6_7', label: '6–7', value: '6_7' },
        { id: '7_9', label: '7–9', value: '7_9' },
        { id: 'more_9', label: 'More than 9', value: 'more_9' },
      ],
    },
    {
      id: 'sitting_hours',
      section: 'Lifestyle',
      label: 'How many hours per day do you spend sitting?',
      type: 'single_choice',
      options: [
        { id: 'less_3', label: 'Less than 3', value: 'less_3' },
        { id: '3_5', label: '3–5', value: '3_5' },
        { id: '6_8', label: '6–8', value: '6_8' },
        { id: '8_10', label: '8–10', value: '8_10' },
        { id: 'more_10', label: 'More than 10', value: 'more_10' },
      ],
    },
    {
      id: 'daily_steps',
      section: 'Lifestyle',
      label: 'Approximately how many steps do you walk each day?',
      type: 'single_choice',
      options: [
        { id: 'less_3k', label: '🚶 Less than 3,000', value: 'less_3k' },
        { id: '3k_5k', label: '🚶 3,000–5,000', value: '3k_5k' },
        { id: '5k_8k', label: '🏃 5,000–8,000', value: '5k_8k' },
        { id: '8k_10k', label: '🏃 8,000–10,000', value: '8k_10k' },
        { id: 'more_10k', label: '🔥 More than 10,000', value: 'more_10k' },
      ],
    },
    {
      id: 'confidence',
      section: 'Mindset',
      label: 'How confident are you that you can achieve your goal?',
      type: 'scale',
      options: [
        { id: 'low', label: '😎 Not at all', value: 1 },
        { id: 'high', label: '😩 Very confident', value: 10 },
      ],
    },
    {
      id: 'motivation',
      section: 'Mindset',
      label: 'How motivated are you to make lifestyle changes?',
      type: 'scale',
      options: [
        { id: 'low', label: '❌ Not motivated', value: 1 },
        { id: 'high', label: '🔥 Highly motivated', value: 10 },
      ],
    },
    {
      id: 'support_system',
      section: 'Mindset',
      label: 'Who supports your health journey the most?',
      type: 'single_choice',
      options: [
        { id: 'family', label: '👨‍👩‍👧‍👦 Family', value: 'family' },
        { id: 'friends', label: '👥 Friends', value: 'friends' },
        { id: 'coach', label: '🏆 Coach', value: 'coach' },
        { id: 'no_one', label: '❌ No one', value: 'no_one' },
        { id: 'prefer_not', label: '🤐 Prefer not to say', value: 'prefer_not' },
      ],
    },
    {
      id: 'easiest_habit',
      section: 'Readiness',
      label: 'Which healthy habit would be easiest for you to improve first?',
      type: 'single_choice',
      options: [
        { id: 'eat_healthier', label: 'Eat healthier', value: 'eat_healthier' },
        { id: 'exercise', label: '🏋️ Exercise', value: 'exercise' },
        { id: 'sleep', label: '😴 Sleep', value: 'sleep' },
        { id: 'water', label: 'Drink more water', value: 'water' },
        { id: 'sugar', label: 'Reduce sugar', value: 'sugar' },
        { id: 'stress', label: 'Reduce stress', value: 'stress' },
      ],
    },
    {
      id: 'hardest_habit',
      section: 'Readiness',
      label: 'Which healthy habit feels most difficult?',
      type: 'single_choice',
      options: [
        { id: 'eat_healthier', label: '🥗 Healthy eating', value: 'eat_healthier' },
        { id: 'exercise', label: '🏋️ Exercise', value: 'exercise' },
        { id: 'sleep', label: '😴 Sleep', value: 'sleep' },
        { id: 'stress', label: 'Stress management', value: 'stress' },
        { id: 'consistency', label: '🔁 Consistency', value: 'consistency' },
      ],
    },
    {
      id: 'commitment',
      section: 'Readiness',
      label: 'How committed are you to improving your weight over the next 90 days?',
      type: 'scale',
      options: [
        { id: 'low', label: '❌ Not committed', value: 1 },
        { id: 'high', label: '💪 Very committed', value: 10 },
      ],
    },
  ];
