import { Metadata } from 'next';
import { LegalPage } from '@/components/layout/legal-page';

export const metadata: Metadata = {
  title: 'Medical Disclaimer | WelliQo',
  description: 'Important medical and health disclaimers regarding the use of WelliQo services.',
};

export default function MedicalDisclaimerPage() {
  return (
    <LegalPage title="Medical & Health Disclaimer" lastUpdated="August 8, 2026">
      <p>
        This Medical Disclaimer applies to all services, content, reports, algorithms, text, graphics, images, and other materials provided by WelliQo and VeeiQ Technologies (the "Company", "we", "us", or "our") through our website, mobile applications, and direct communications (collectively, the "Services").
      </p>
      <p>
        <strong>By using the Services, you explicitly agree to this Medical Disclaimer. If you do not agree, you must immediately cease use of the Services.</strong>
      </p>

      <h2>1. Not Medical Advice</h2>
      <p>
        The content provided by WelliQo is for <strong>informational and educational purposes only</strong>. We are a wellness technology platform, not a hospital, clinic, or medical facility. 
      </p>
      <p>
        Our algorithms, health baselines, nutritional insights, and coaching recommendations DO NOT constitute medical advice, medical diagnosis, psychiatric advice, or medical treatment. You should never rely on information provided by WelliQo as a substitute for, nor does it replace, professional medical advice, diagnosis, or treatment from a licensed healthcare provider.
      </p>

      <h2>2. No Doctor-Patient Relationship</h2>
      <p>
        Using WelliQo, taking our assessments, or interacting with our platform and wellness coaches does not establish a doctor-patient, therapist-client, or other healthcare professional relationship between you and WelliQo or any of its employees or affiliates.
      </p>

      <h2>3. Seek Professional Consultation</h2>
      <p>
        Always seek the advice of your physician or other qualified healthcare provider with any questions you may have regarding a medical condition, dietary changes, new exercise regimens, or wellness goals. 
      </p>
      <ul>
        <li>Do not disregard professional medical advice or delay in seeking it because of something you have read on the WelliQo platform.</li>
        <li>If you think you may have a medical emergency, call your doctor or emergency services (such as 911 in the US or 112/999/108 internationally) immediately.</li>
      </ul>

      <h2>4. Pre-existing Conditions and Risks</h2>
      <p>
        Wellness initiatives, including dietary modifications and physical activity, carry inherent risks. If you are pregnant, nursing, diabetic, have a cardiovascular condition, suffer from an eating disorder, or have any other chronic or acute medical condition, you are strictly advised to consult a physician before using our Services or acting on any insights generated by our platform.
      </p>
      <p>
        The Company makes no guarantees concerning the level of success you may experience, and you accept the risk that results will differ for each individual. The testimonials and examples provided are exceptional results, which do not apply to the average purchaser, and are not intended to represent or guarantee that anyone will achieve the same or similar results.
      </p>

      <h2>5. Nutritional and Dietary Information</h2>
      <p>
        WelliQo provides nutritional information and dietary suggestions based on broad algorithms and behavioral science. This information is not meant to prescribe diets for the treatment of diseases. It is your responsibility to verify any food allergies, intolerances, or drug interactions with your healthcare provider.
      </p>

      <h2>6. Accuracy of Information</h2>
      <p>
        While we strive to keep our information science-informed and up-to-date, medical science evolves rapidly. We cannot guarantee that all information provided by the Service reflects the most recent medical research. We assume no liability for errors or omissions in our content.
      </p>

      <h2>7. Assumption of Risk and Release of Liability</h2>
      <p>
        You expressly acknowledge and agree that your access, use, and reliance on the Services are at your own sole risk. You hereby release, indemnify, and hold harmless VeeiQ Technologies, its directors, officers, employees, and agents from any and all claims, demands, damages, rights of action, or causes of action, present or future, arising out of or connected with your use of the Services, including any injuries or illness resulting from your adherence to our wellness insights.
      </p>

      <h2>8. Contact</h2>
      <p>
        If you have questions regarding this Medical Disclaimer, please contact our legal team at legal@veeiq.com.
      </p>
    </LegalPage>
  );
}
