import { QuestionDef, QuestionOption, QuestionType } from '../types/assessment';

export const UNIVERSAL_PROFILE_QUESTIONS: QuestionDef[] = [
  {
    id: 'name',
    section: '🧍 About You',
    label: 'What is your full name?',
    type: 'text',
    placeholder: 'Enter your full name',
    required: false,
    intro: '👋 First, let\'s get to know you.',
    why: 'Used to personalize your dashboard and reports.',
  },
  {
    id: 'age',
    section: '🧍 About You',
    label: 'How old are you?',
    type: 'number',
    placeholder: 'Age',
    required: true,
    why: 'Used to personalize health benchmarks and recommendations.',
  },
  {
    id: 'gender',
    section: '🧍 About You',
    label: 'What is your gender?',
    type: 'single_choice',
    options: [
      { id: 'male', label: '👨 Male', value: 'male' },
      { id: 'female', label: '👩 Female', value: 'female' },
      { id: 'other', label: '🌈 Other', value: 'other' },
    ],
    required: true,
    why: 'Helps us tailor your biometric ranges and insights.',
  },
  {
    id: 'height',
    section: '📏 Health Profile',
    label: 'How tall are you?',
    type: 'height',
    required: true,
    intro: 'Let\'s build your physical baseline.',
    why: 'Used to calculate BMI and healthy weight.',
  },
  {
    id: 'weight',
    section: '📏 Health Profile',
    label: 'What is your current weight?',
    type: 'weight',
    required: true,
    why: 'Used to personalize calories and protein.',
  },
  {
    id: 'conditions',
    section: '📏 Health Profile',
    label: 'Do you have any known medical conditions?',
    type: 'multiple_choice',
    options: [
      { id: 'none', label: '✨ None', value: 'none' },
      { id: 'diabetes', label: '🩸 Diabetes', value: 'diabetes' },
      { id: 'hbp', label: '🫀 High Blood Pressure', value: 'hbp' },
      { id: 'thyroid', label: '🦋 Thyroid', value: 'thyroid' },
      { id: 'heart', label: '❤️ Heart Disease', value: 'heart' },
      { id: 'pcos', label: '🌸 PCOS', value: 'pcos' },
      { id: 'asthma', label: '🫁 Asthma', value: 'asthma' },
      { id: 'cholesterol', label: '🍔 High Cholesterol', value: 'cholesterol' },
      { id: 'other', label: '🩺 Other', value: 'other' },
    ],
    intro: 'Your safety is our priority.',
    why: 'Ensures we provide safe and appropriate recommendations.',
  },
  {
    id: 'occupation',
    section: '🥗 Nutrition & Lifestyle',
    label: 'What is your occupation?',
    type: 'single_choice',
    options: [
      { id: 'student', label: '🎓 Student', value: 'student' },
      { id: 'professional', label: '💼 Working Professional', value: 'professional' },
      { id: 'business', label: '🚀 Business Owner', value: 'business' },
      { id: 'homemaker', label: '🏡 Homemaker', value: 'homemaker' },
      { id: 'retired', label: '🏖️ Retired', value: 'retired' },
      { id: 'other', label: '✨ Other', value: 'other' },
    ],
    intro: 'Now, let\'s look at your daily routine.',
  },
  {
    id: 'activityLevel',
    section: '🏃 Activity',
    label: 'How would you describe your daily activity?',
    type: 'single_choice',
    options: [
      { id: 'sedentary', label: '🪑 Not Active', value: 'sedentary', description: 'Little to no exercise' },
      { id: 'light', label: '🚶 Lightly Active', value: 'light', description: '1-3 days/week' },
      { id: 'moderate', label: '🏃 Moderately Active', value: 'moderate', description: '3-5 days/week' },
      { id: 'active', label: '🏋️ Very Active', value: 'active', description: '6-7 days/week' },
    ],
    why: 'Used to calculate your daily energy expenditure.',
  },
  {
    id: 'food_preference',
    section: '🥗 Nutrition & Lifestyle',
    label: 'What is your food preference?',
    type: 'single_choice',
    options: [
      { id: 'veg', label: '🥗 Vegetarian', value: 'vegetarian' },
      { id: 'egg', label: '🍳 Eggetarian', value: 'eggetarian' },
      { id: 'nonveg', label: '🍗 Non-Vegetarian', value: 'non_vegetarian' },
      { id: 'vegan', label: '🌱 Vegan', value: 'vegan' },
      { id: 'jain', label: '🧘 Jain', value: 'jain' },
      { id: 'other', label: '🍽️ Other', value: 'other' },
    ],
    intro: 'Let\'s talk about your eating habits.',
  },
  {
    id: 'smoking',
    section: '🥗 Nutrition & Lifestyle',
    label: 'Do you smoke or use tobacco products?',
    type: 'single_choice',
    options: [
      { id: 'no', label: '🚭 No', value: 'no' },
      { id: 'occasionally', label: '🚬 Occasionally', value: 'occasionally' },
      { id: 'regularly', label: '😮‍💨 Regularly', value: 'regularly' },
    ],
    why: 'Helps us understand your cardiovascular health risk.',
  },
  {
    id: 'alcohol',
    section: '🥗 Nutrition & Lifestyle',
    label: 'How often do you consume alcohol?',
    type: 'single_choice',
    options: [
      { id: 'no', label: '🚫 No', value: 'no' },
      { id: 'occasionally', label: '🥂 Occasionally', value: 'occasionally' },
      { id: 'regularly', label: '🍻 Regularly', value: 'regularly' },
    ],
    why: 'Affects metabolism, sleep, and long-term health goals.',
  },
];

