import { QuestionDef } from '@/types/assessment';

export const questions: QuestionDef[] = [
  {
    id: 'portion_control',
    section: 'Nutrition & Calorie Control',
    label: 'How often do you consciously control your food portions?',
    type: 'single_choice',
    options: [
      { id: 'every_meal', label: '🍽️ Every meal', value: 'every_meal' },
      { id: 'most_meals', label: '📏 Most meals', value: 'most_meals' },
      { id: 'occasionally', label: '🤔 Occasionally', value: 'occasionally' },
      { id: 'never', label: '❌ Never', value: 'never' },
    ],
    required: true,
  },
  {
    id: 'restaurant_food',
    section: 'Nutrition & Calorie Control',
    label: 'How often do you eat restaurant, takeaway or fast food?',
    type: 'single_choice',
    options: [
      { id: 'rarely', label: 'Rarely', value: 'rarely' },
      { id: 'once_week', label: 'Once a week', value: 'once_week' },
      { id: '2_3_week', label: '2–3 times/week', value: '2_3_week' },
      { id: '4_plus', label: '4+ times/week', value: '4_plus' },
    ],
  },
  {
    id: 'sugary_drinks_fl',
    section: 'Nutrition & Calorie Control',
    label: 'How many sugar-sweetened drinks do you consume weekly?',
    type: 'single_choice',
    options: [
      { id: 'none', label: 'None', value: 'none' },
      { id: '1_2', label: '1–2', value: '1_2' },
      { id: '3_6', label: '3–6', value: '3_6' },
      { id: 'daily', label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'protein_intake',
    section: 'Nutrition & Calorie Control',
    label: 'How often do you include a good source of protein in every meal?',
    type: 'single_choice',
    options: [
      { id: 'every_meal', label: 'Every meal', value: 'every_meal' },
      { id: 'most_meals', label: 'Most meals', value: 'most_meals' },
      { id: 'sometimes', label: 'Sometimes', value: 'sometimes' },
      { id: 'rarely', label: 'Rarely', value: 'rarely' },
    ],
  },
  {
    id: 'mindless_snacking',
    section: 'Nutrition & Calorie Control',
    label: 'How often do you snack between meals without feeling physically hungry?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'frequently', label: 'Frequently', value: 'frequently' },
      { id: 'daily', label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'late_eating_fl',
    section: 'Nutrition & Calorie Control',
    label: 'How often do you eat within 2 hours before going to bed?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'most_days', label: 'Most days', value: 'most_days' },
      { id: 'every_day', label: 'Every day', value: 'every_day' },
    ],
  },
  {
    id: 'weekend_eating',
    section: 'Nutrition & Calorie Control',
    label: 'Are your eating habits different on weekends?',
    type: 'single_choice',
    options: [
      { id: 'same', label: 'Same as weekdays', value: 'same' },
      { id: 'worse', label: 'Slightly worse', value: 'worse' },
      { id: 'much_worse', label: 'Much worse', value: 'much_worse' },
      { id: 'uncontrolled', label: 'Completely uncontrolled', value: 'uncontrolled' },
    ],
  },
  {
    id: 'daily_steps_fl',
    section: 'Activity & Muscle Preservation',
    label: 'Average daily steps?',
    type: 'single_choice',
    options: [
      { id: '10k_plus', label: '10,000+', value: '10k_plus' },
      { id: '7k_10k', label: '7,000–10,000', value: '7k_10k' },
      { id: '4k_7k', label: '4,000–7,000', value: '4k_7k' },
      { id: 'below_4k', label: 'Below 4,000', value: 'below_4k' },
    ],
  },
  {
    id: 'strength_training',
    section: 'Activity & Muscle Preservation',
    label: 'How many days per week do you perform resistance training?',
    type: 'single_choice',
    options: [
      { id: '4_plus', label: '4+', value: '4_plus' },
      { id: '2_3', label: '2–3', value: '2_3' },
      { id: '1', label: '1', value: '1' },
      { id: 'none', label: 'None', value: 'none' },
    ],
  },
  {
    id: 'cardio',
    section: 'Activity & Muscle Preservation',
    label: 'How many days per week do you perform cardio?',
    type: 'single_choice',
    options: [
      { id: '5_plus', label: '5+', value: '5_plus' },
      { id: '3_4', label: '3–4', value: '3_4' },
      { id: '1_2', label: '1–2', value: '1_2' },
      { id: 'none', label: 'None', value: 'none' },
    ],
  },
  {
    id: 'seated_hours',
    section: 'Activity & Muscle Preservation',
    label: 'How many hours do you remain seated each day?',
    type: 'single_choice',
    options: [
      { id: 'less_4', label: '<4', value: 'less_4' },
      { id: '4_6', label: '4–6', value: '4_6' },
      { id: '7_9', label: '7–9', value: '7_9' },
      { id: '10_plus', label: '10+', value: '10_plus' },
    ],
  },
  {
    id: 'work_movement',
    section: 'Activity & Muscle Preservation',
    label: 'During work, how often do you get up and move every hour?',
    type: 'single_choice',
    options: [
      { id: 'always', label: 'Always', value: 'always' },
      { id: 'often', label: 'Often', value: 'often' },
      { id: 'sometimes', label: 'Sometimes', value: 'sometimes' },
      { id: 'never', label: 'Never', value: 'never' },
    ],
  },
  {
    id: 'daily_routine',
    section: 'Activity & Muscle Preservation',
    label: 'Which statement best describes your daily routine?',
    type: 'single_choice',
    options: [
      { id: 'highly_active', label: 'Highly active', value: 'highly_active' },
      { id: 'moderately_active', label: 'Moderately active', value: 'moderately_active' },
      { id: 'mostly_sitting', label: 'Mostly sitting', value: 'mostly_sitting' },
      { id: 'inactive', label: 'Almost completely inactive', value: 'inactive' },
    ],
  },
  {
    id: 'sugar_cravings',
    section: 'Metabolic Efficiency',
    label: 'Do you experience strong sugar cravings?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'frequently', label: 'Frequently', value: 'frequently' },
      { id: 'daily', label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'satiety',
    section: 'Metabolic Efficiency',
    label: 'How soon after meals do you feel hungry again?',
    type: 'single_choice',
    options: [
      { id: '4_plus', label: '4+ hours', value: '4_plus' },
      { id: '3_4', label: '3–4 hours', value: '3_4' },
      { id: '2_3', label: '2–3 hours', value: '2_3' },
      { id: 'less_2', label: '<2 hours', value: 'less_2' },
    ],
  },
  {
    id: 'energy_crashes',
    section: 'Metabolic Efficiency',
    label: 'Do you experience afternoon energy crashes?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'frequently', label: 'Frequently', value: 'frequently' },
      { id: 'daily', label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'weight_plateau',
    section: 'Metabolic Efficiency',
    label: 'Have you stopped losing weight despite trying consistently?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'sometimes', label: 'Sometimes', value: 'sometimes' },
      { id: 'yes', label: 'Yes', value: 'yes' },
      { id: 'unsure', label: 'Unsure', value: 'unsure' },
    ],
  },
  {
    id: 'compensatory_eating',
    section: 'Metabolic Efficiency',
    label: 'How often do you skip meals and then overeat later?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'frequently', label: 'Frequently', value: 'frequently' },
      { id: 'daily', label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'sleep_hours_fl',
    section: 'Recovery & Hormonal Balance',
    label: 'How many hours do you usually sleep?',
    type: 'single_choice',
    options: [
      { id: '7_9', label: '7–9', value: '7_9' },
      { id: '6_7', label: '6–7', value: '6_7' },
      { id: '5_6', label: '5–6', value: '5_6' },
      { id: 'less_5', label: '<5', value: 'less_5' },
    ],
  },
  {
    id: 'stress_level',
    section: 'Recovery & Hormonal Balance',
    label: 'How stressed do you feel most days?',
    type: 'single_choice',
    options: [
      { id: 'low', label: 'Low', value: 'low' },
      { id: 'moderate', label: 'Moderate', value: 'moderate' },
      { id: 'high', label: 'High', value: 'high' },
      { id: 'extremely_high', label: 'Extremely High', value: 'extremely_high' },
    ],
  },
  {
    id: 'wake_refreshed',
    section: 'Recovery & Hormonal Balance',
    label: 'Do you wake feeling refreshed?',
    type: 'single_choice',
    options: [
      { id: 'always', label: 'Always', value: 'always' },
      { id: 'usually', label: 'Usually', value: 'usually' },
      { id: 'rarely', label: 'Rarely', value: 'rarely' },
      { id: 'never', label: 'Never', value: 'never' },
    ],
  },
  {
    id: 'daily_energy',
    section: 'Recovery & Hormonal Balance',
    label: 'How would you rate your energy throughout the day?',
    type: 'single_choice',
    options: [
      { id: 'excellent', label: 'Excellent', value: 'excellent' },
      { id: 'good', label: 'Good', value: 'good' },
      { id: 'average', label: 'Average', value: 'average' },
      { id: 'poor', label: 'Poor', value: 'poor' },
    ],
  },
  {
    id: 'emotional_eating_fl',
    section: 'Behaviour & Long-term Consistency',
    label: 'When stressed, how often do you eat for comfort?',
    type: 'single_choice',
    options: [
      { id: 'never', label: 'Never', value: 'never' },
      { id: 'occasionally', label: 'Occasionally', value: 'occasionally' },
      { id: 'frequently', label: 'Frequently', value: 'frequently' },
      { id: 'always', label: 'Almost Always', value: 'always' },
    ],
  },
  {
    id: 'biggest_obstacle_fl',
    section: 'Behaviour & Long-term Consistency',
    label: 'What is your biggest obstacle to losing fat?',
    type: 'single_choice',
    options: [
      { id: 'consistency', label: 'Lack of consistency', value: 'consistency' },
      { id: 'hunger', label: 'Hunger & cravings', value: 'hunger' },
      { id: 'schedule', label: 'Busy schedule', value: 'schedule' },
      { id: 'motivation', label: 'Lack of motivation', value: 'motivation' },
      { id: 'social', label: 'Social/family eating', value: 'social' },
      { id: 'unsure', label: 'Unsure', value: 'unsure' },
    ],
  },
  {
    id: 'commitment_fl',
    section: 'Behaviour & Long-term Consistency',
    label: 'How committed are you to changing your habits over the next 90 days?',
    type: 'scale',
    options: [
      { id: 'low', label: 'Not committed', value: 1 },
      { id: 'high', label: 'Very committed', value: 10 },
    ],
  },
];
